### PR TITLE
Update documentation for `cached` and backends

### PR DESCRIPTION
**Pull request by fdegiuli**
As per https://github.com/groupon/node-cached/issues/26

### CODE REVIEW

**Comment by fdegiuli** [comment]
You guys don't like console statements. Should I get rid of it, or just turn it into an error instead and you can bump the version number?

**Comment by jkrems** [comment]
You can use [`util.deprecate`](https://nodejs.org/api/util.html#util_util_deprecate_function_string). The advantage of that function is that the warning will only be logged once, not on each access. This can be important in high traffic applications where the additional output could otherwise have performance implications. E.g.:

```js
var getDefaultName = deprecate(function getDefaultName() {
  return 'default';
}, 'The actual warning');
// ...
if (badThing) { name = getDefaultName(); }
```

**Comment by fdegiuli** [comment]
Never knew about that thing, thanks!  

Sorry for the delay, should be fixed now.

**Comment by fdegiuli** [comment]
So much git rebase 😢

**Comment by jkrems** [comment]
Yeah, it takes some getting used to. But the automation it enables is worth it. :) Thanks for this, much appreciated! Sorry for being a bit slow to respond, busy week.

:shipit:

**Pull request merged**
